roads = [
    "The Avenue",
    "Spring Lane",
    "Fairfield Lane",
    "Gregory Road",
    "Mayflower Way",
    "Langtons Meadow",
    "Parsonage Lane",
    "Sospel Court",
    "Jones Way",
    "Stoke Wood",
    "Vine Road",
    "Rogers Lane",
    "Duffield Park",
    "Lynch Hill Lane",
    "Rokesby Road",
    "Doddsfield Road",
    "Pemberton Road",
    "Cowper Road",
    "Crofthill Road",
    # "Lammas Road",
    # "Royston Way",
    # "Stanhope Road",
    # "Blumfield Crescent",
    # "Scafell Road",
    # "Greenside",
    # "Furnival Avenue",
    # "Birch Grove",
    # "Cornwall Avenue",
    # "Surrey Avenue",
    # "Hampshire Avenue",
    # "Sheffield Road",
    # "Villiers Road",
    # "Howard Avenue",
    # "Waterbeach Road",
    # "Leeds Road",
    # "Lake Avenue",
    # "Hawthorne Crescent",
    # "Myrtle Crescent",
    # "Montague Road",
    # "Queens Road",
    # "Salt Hill Way",
    # "Lansdowne Avenue",
    # "Black Pond Lane",
    # "St. Georges Crescent",
    # "Harrison Way",
    # "Washington Drive",
    # "Barnfield",
    # "Stowe Road",
    # "Bower Way",
    # "Bowyer Drive",
    # "Robin Hood Close",
    # "Boarlands Close",
    # "Bennetts Close",
    # "Amerden Way",
    # "Bader Gardens",
    # "Mitchell Close",
    # "Cranbourne Road",
    # "Weekes Drive",
    # "Chalvey Grove",
    # "Darvill’s Lane",
    # "Clive Court",
    # "Hillside",
    # "The Crescent",
    # "Richards Way",
    # "Moor Furlong",
    # "Graylands Close",
    # "Kenbury Drive",
    # "Spackmans Way",
]
